#include "nsISupports.idl"
#include "nsITimer.idl"
#include "nsIServiceManager.idl"

[scriptable, uuid(3DA74016-FBF0-4088-A7B6-82C57EE90D52)]

interface IDSDREGISTER : nsISupports
{
	// Register service
	
	void start();
	
	// Remove registration
	
	void stop();
	
	// Interface to register on 
	
	attribute long interfaceIndex;

    // Auto rename in case of naming conflict
    
    attribute PRBool autorename;
    
    // Service name

	attribute AString name;
    
    // Service registration type

	attribute AString registrationType;

    // Service registration domain
    
    attribute AString registrationDomain;
    
    // Target host

	attribute AString targetHost;
    
    // Port
    
	attribute long targetPort;

    // Text record key
    
    attribute AString txtRecordKey;

    // Text record value
    
    attribute AString txtRecordValue;
		
	// Last flags supplied by DNSServiceRegister
	
	readonly attribute long lastFlags;
	
	// Last error code from DNSServiceRegister
	
	readonly attribute long lastErrorcode;
	
	// Last service name, or renamed supplied by DNSServiceRegister
	
	readonly attribute AString lastName;
	
	// Registration type as supplied to DNSServiceRegister
	
	readonly attribute AString lastRegType;
	
	// Last domain service registered in
	
	readonly attribute AString lastDomain;

	// Wrappers state

	readonly attribute long status;	
};
