#include "nsISupports.idl"
#include "nsITimer.idl"
#include "nsIServiceManager.idl"

[scriptable, uuid(C38472D2-9010-4899-B2AE-89ADC8EB1246)]

interface IDSDBROWSE : nsISupports
{
	// Start browsing for services
	
	void start();
	
	// Stop looking for services
	
	void stop();
	
	// Interface to search on
	
	attribute long interfaceIndex;
	
	// Registration type to look for
	
	attribute AString registrationType;
	
	// Domain to look for services in
	
	attribute AString registrationDomain;
	
	// Last flags supplied by DNSServiceBrowse
	
	readonly attribute long lastFlags;
	
	// Last interfaceIndex supplied by DNSServiceBrowse
	
	readonly attribute long lastInterface;
	
	// Last error code from DNSServiceBrowse
	
	readonly attribute long lastErrorcode;
	
	// Last service name found by DNSServiceBrowse
	
	readonly attribute AString lastName;
	
	// Last service found's registration type
	
	readonly attribute AString lastRegType;
	
	// Last domain service found in
	
	readonly attribute AString lastDomain;

	// Wrappers state

	readonly attribute long status;	
};
